### ISSUE TITLE
Tugboat auto deletion

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#541]
## Description
Next Build Issue:
Tugboat which is used to create our preview environments when creating a pull request has the tendency to fail if we have reached our storage capacity on the tugboat server. The current solution is to manually delete old environments to resolve this issue. As manual deletion is not sustainable we will need the ability to have tugboat automatically delete environments after 14 days. The documentation for Tugboat is not great but a link to it can be found inside of the supporting details section.

## Acceptance Criteria
- [ ] Tugboat will automatically remove environments that are 14 days or older.
- [ ] Any current environments over 14 days should be deleted.
- [ ] [Tugboat Readme](https://github.com/department-of-veterans-affairs/next-build/blob/main/READMEs/tugboat.md) is updated with how this process is done.

## Supporting detail
**Tugboat Docs**: https://docs.tugboatqa.com/building-a-preview/administer-previews/delete-previews/

**TTL**: I have not been able to confirm that the following will work as I can not find it documented anywhere inside of the Tugboat docs, however it MAY be possible to modify the Tugboat config.yml file and add a ttl. This ttl accepts time in seconds. This solution may not work but would be the best solution, example code below.

```
services:
  php:
    image: tugboatqa/php:7.3
    default: true
    commands:
      init:
        - composer install
    ttl: 604800  # Set TTL to 7 days (7 days * 24 hours * 60 minutes * 60 seconds)
```

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [x] `Accelerated Publishing`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
